When ServiceUnavailable, log error instead of exception (traceback) (#764)
* Don't log exception on 503 Service Unavailable but log error

503 status is not an unexpected error. Quite common btw
Also OpenSubtitle raises a xmlrpclib.ProtocolError when unavailable:
<ProtocolError for api.opensubtitles.org/xml-rpc: 503 Backend fetch failed>

Full traceback:

Unexpected error in provider 'opensubtitles'
Traceback (most recent call last):
  File "/home/osmc/Medusa/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/home/osmc/Medusa/lib/subliminal/core.py", line 68, in __getitem__
    provider.initialize()
  File "/home/osmc/Medusa/lib/subliminal/providers/opensubtitles.py", line 142, in initialize
    'subliminal v%s' % __short_version__))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1321, in single_request
    response.msg,
ProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Backend fetch failed>

* LegendasTV need a custom function as it returns 200 when unavailable

* Proper handle empty content in Addic7ed

Provider wrongful return a status of 304 Not Modified with an empty content
raise_for_status won't raise exception for that status code

* Review